apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raven-agent-ds
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "raven-agent.appLabels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "raven-agent.appLabels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: raven-agent
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- with .Values.containerEnv }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
          - --v=2
          - --vpn-driver={{.Values.vpn.driver}}
          - --forward-node-ip={{.Values.vpn.forwardNodeIP}}
          - --metric-bind-addr={{.Values.vpn.metricBindAddr}}
          - --vpn-bind-port={{.Values.vpn.tunnelAddr}}
          - --proxy-metric-bind-addr={{.Values.proxy.metricsBindAddr}}
          - --proxy-internal-secure-addr={{.Values.proxy.internalSecureAddr}}
          - --proxy-internal-insecure-addr={{.Values.proxy.internalInsecureAddr}}
          - --proxy-external-addr={{.Values.proxy.externalAddr}}

      hostNetwork: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
