apiVersion: v1
kind: ServiceAccount
metadata:
  name: raven-agent-account
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: raven-agent-role
rules:
  - apiGroups:
      - raven.openyurt.io
    resources:
      - gateways
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - nodes
      - pods
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - create
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: raven-agent-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: raven-agent-role
subjects:
  - kind: ServiceAccount
    name: raven-agent-account
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: raven-proxy-user
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/stats
      - nodes/metrics
      - nodes/log
      - nodes/spec
      - nodes/proxy
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raven-proxy-user-binding
subjects:
  - kind: User
    name: tunnel-proxy-client
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: raven-proxy-user
  apiGroup: rbac.authorization.k8s.io
---